# Generated by Django 3.2.15 on 2022-11-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221109_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_phone_active',
            new_name='is_phone_valid',
        ),
    ]
