version: "3.1"
services:
  web:
    build: .
    command:
      - python3
      - manage.py
      - runserver
      - 0:8700
    ports:
      - 8700:8700
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data:
