version: "3.1"
services:
  web:
    build: .
    command: gunicorn shop.wsgi
    ports:
     - ${GUNICORN_PORT}:${GUNICORN_PORT}
    volumes:
      - .:/code
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - celery
      - celery-beat
      - memcached
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
  redis:
    image: redis:latest
    restart: always
  celery:
    build: .
    command: celery -A shop worker -l INFO
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A shop beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
  memcached:
    image: memcached:latest
    restart: always
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env


volumes:
  postgres_data:
