# Generated by Django 3.2.15 on 2022-11-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('favourites', '0002_favourites_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='products',
        ),
        migrations.AddField(
            model_name='favourites',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
