# Generated by Django 3.2.15 on 2022-12-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_used'),
        ('favourites', '0003_auto_20221107_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='products',
            field=models.ManyToManyField(related_name='in_favourites', to='products.Product'),
        ),
    ]
