# Generated by Django 3.2.15 on 2022-12-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_config_contact_form_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='contact_form_email',
            field=models.EmailField(default='savochkinoleg17@gmail.com', max_length=254),
        ),
    ]
