# Generated by Django 3.2.15 on 2022-11-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static/images/products/no_image.jpg', upload_to='images/category'),
        ),
    ]
