# Generated by Django 3.2.15 on 2022-11-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
